### ISSUE TITLE
Don't wait hothend temperature in chamber soak

### ISSUE THREAD

**Issue by elpopo-eng** [Frix-x/klippain#143]
Just change the M109 in M104 it's not needed to wait hotend temp before chamber soak.
And if chamber and hotend (temp > safe temp) is already hot it's just waiting hothend cooldown of hotend.

Before
```
# Heat the hotend to the safe temperature to spread some heat as well
M109 S{safe_extruder_temp}
```

Fix
```
# Heat the hotend to the safe temperature to spread some heat as well
M104 S{safe_extruder_temp}
```

**Comment by Frix-x** [comment]
Yes you're right. I'll correct that in the next release :)

**Comment by Frix-x** [comment]
This is fixed in https://github.com/Frix-x/klippain/pull/149/commits/531c338207e5625791a678cc2b511a87bb2724af
