### ISSUE TITLE
modular start_print issue

### ISSUE THREAD

**Issue by jeronbernal** [Frix-x/klippain#150]
getting a error when trying to add the primeline to my start print via variable_startprint_actions: "primeline"
	
	i get a error of Error evaluating 'gcode_macro START_PRINT:gcode': gcode.CommandError: Unknown module called in START_PRINT! Please verify your startprint_actions variable override!
![image](https://user-images.githubusercontent.com/74906164/232324921-946d0d9d-786d-4009-9390-fb83f2635a26.png)
![image (1)](https://user-images.githubusercontent.com/74906164/232324968-8d11369c-c607-439d-a19b-4c9907e8e8ec.png)

**Comment by jeronbernal** [comment]
tried to use 3.1.0 and put it in the override.cfg but get this issue 

![image](https://user-images.githubusercontent.com/74906164/232327917-adafc3cc-7b36-4eff-aafc-37fadbe63b81.png)
![image](https://user-images.githubusercontent.com/74906164/232327934-239a4015-9b88-4e63-9019-e6e6e01dd27f.png)

**Comment by Benoitone** [comment]
Maybe you can't use only primeline ?

**Comment by Frix-x** [comment]
Yes Benoitone is right. This variable is expected to be a list of action and in Jinja it need at least two elements.

@Benoitone, I'm already discussing with him in the Klippain channel of the Voron Discord. So I'll close this issue as the solution is found :)
