### ISSUE TITLE
MCU_UARTS not defined correctly on BTT_SKR_E3mini_v2.cfg

### ISSUE THREAD

**Issue by AMFkuna** [Frix-x/klippain#154]
Hi 
I can implement Klippain to my V0 printer, but mcu uarts not defined in BTT_SKR_E3mini_v2.cfg
1.8d_xy_V0specific.cfg and V0_1.8d_TR8x8_z.cfgmust be reworked

It would be good to edit V0_specific.cfg and add uart_addresses and tx_pin definition.

**Comment by Frix-x** [comment]
The thing is that there is no way to "remove" something already declared. So if I declare by default the UART in the V0 axis cfg, then all the user of other board will not be able to use them as they will not be able to remove it.

However the opposite is really easy: it's done using the overrides.cfg file. So, in your case you need to:
  1. enable the v0 files from printer.cfg
  2. add the uart definition to your overrides that way:
```
[tmc2209 stepper_x]
uart_pin: MCU_TMCUART
tx_pin: MCU_TMCTX
uart_address: 0

[tmc2209 stepper_y]
uart_pin: MCU_TMCUART
tx_pin: MCU_TMCTX
uart_address: 2

[tmc2209 stepper_z]
uart_pin: MCU_TMCUART
tx_pin: MCU_TMCTX
uart_address: 1
```

**Comment by AMFkuna** [comment]
Yes I did that, but in mcu_defaults there must not be defined uarts X_TMCUART=MCU_XM_UART for BTT_SKR_E3mini
![Snímek obrazovky 2023-04-25 v 9 33 40](https://user-images.githubusercontent.com/17743216/234206372-c52e763c-8e28-4d9b-a894-cebd0d0a269d.jpg)

**Comment by Surion79** [comment]
yeah, I have a local branch for the SKR Pico which has the same type of configuration. that does not work (anymore?)

**Comment by Frix-x** [comment]
Closing as Klippain v4 is merged and released :)
