### ISSUE TITLE
Orbiter 2.0 extruder support

### ISSUE THREAD

**Issue by AMFkuna** [Frix-x/klippain#155]
Hi

Should be good to implement Orbiter extruders support.

**Comment by Frix-x** [comment]
I do not see any reason to not include Orbiter extruders. So if you want to open a PR, I'll be happy to merge it :)

**Comment by AMFkuna** [comment]
This is only diferencies from Galileo
```
[extruder]
# Orbiter 2.0
microsteps: 16
#rotation_distance: 4.637       # Orbiter 2 original value
rotation_distance: 4.6805
```

**Comment by Frix-x** [comment]
Then I'll add it in the next release
