### ISSUE TITLE
MCU Toolhead default override X_STOP interferes with Sensorless homing

### ISSUE THREAD

**Issue by Surion79** [Frix-x/klippain#157]
If sensorless homing is used, the default override for toolhead MCU includes a X_STOP definition, making sensorless x homing not possible. Found out by setting it up and wondering why X was moving with the Stallguardvalue of 255

**Comment by Surion79** [comment]
I think it is sufficient to comment out the toolhead x endstop section, not whole. Because there are also set ups that don't use x endstop on the toolhead, because they use the pcb on the X/Y joint

**Comment by Frix-x** [comment]
Done in https://github.com/Frix-x/klippain/commit/eb5083f62286c34aa8f71776a6229a1b04c3a304
