### ISSUE TITLE
Axis resonance test - the PNG file does not contain a datestamp and will overwrite the original file.

### ISSUE THREAD

**Issue by AMFkuna** [Frix-x/klippain#158]
![Snímek obrazovky 2023-04-25 v 10 47 45](https://user-images.githubusercontent.com/17743216/234224417-745d43b5-6c98-4802-860b-a39bace8eff2.jpg)

**Comment by Frix-x** [comment]
This is fixed in https://github.com/Frix-x/klippain/commit/f1cf77a1f3381e749403b3c0a9b279db2d5db402
