### ISSUE TITLE
FLOW_MULTIPLIER_CALIBRATION - disable fan and park at the end of macro

### ISSUE THREAD

**Issue by AMFkuna** [Frix-x/klippain#160]
Should be nice to disable fan and park toolhead at the end of this macro

**Comment by Frix-x** [comment]
Just call your END_PRINT macro at the end. As you would call your START_PRINT to prepare the printer before the calibration.

**Comment by AMFkuna** [comment]
If I call END_PRINT, I lost homing and others, START_PRINT delays again, this macro is used for filament calibration, is very fast to use and is used several times in a row

**Comment by Frix-x** [comment]
Ok I think I understand your need. I'll see if I can work on something

**Comment by Surion79** [comment]
created a PR for it
