### ISSUE TITLE
Adding custom startprint_actions

### ISSUE THREAD

**Issue by Surion79** [Frix-x/klippain#161]
My understanding is that there is a fixed limited number of startprint_actions defined. all values that are not within this pool are erroring out with "unknown module called".
Is it possible to add custom startprint_actions?

**Comment by Surion79** [comment]
sounds great. if it is just added in the print start file, you can write the hidden documentation in the bare custom modules gcode_marco sections. that would basically mean only changing one file

**Comment by AMFkuna** [comment]
You can use unused module and override it with your customs.

**Comment by Surion79** [comment]
added a PR for 3 new custom start actions
