### ISSUE TITLE
Link down in adaptive mesh documentation

### ISSUE THREAD

**Issue by coubi64** [Frix-x/klippain#173]
In adaptative bed mesh documentation (https://github.com/Frix-x/klippain/blob/main/docs/features/adaptive_bed_mesh.md), the link to "Exclude Objects guide from the Mainsail team" (https://docs.mainsail.xyz/features/exclude_objects) is down.

The right page is now: https://docs.mainsail.xyz/overview/features/exclude-objects

**Comment by Frix-x** [comment]
Thanks for raising an issue. This will be fixed in the next release :)

**Comment by Frix-x** [comment]
Done in https://github.com/Frix-x/klippain/commit/621bd936d1e3cea40e5a5bd8d7b994680e6ed2e5
