### ISSUE TITLE
Conflict on Trident + TAP : Z position_endstop invalid

### ISSUE THREAD

**Issue by 22MarioZ** [Frix-x/klippain#174]
Hello

I'm using klippain for Trident configuration and I'm geting Klipper error for the following configuration: 
Option 'position_endstop' is not valid in section 'stepper_z'. 

Looks that issue is for the files: [Trident_1.8d_TR8x4_z.cfg](https://github.com/Frix-x/klippain/blob/main/config/hardware/axis/Z/Trident_1.8d_TR8x4_z.cfg) and [Trident_1.8d_TR8x8_z.cfg](https://github.com/Frix-x/klippain/blob/main/config/hardware/axis/Z/Trident_1.8d_TR8x8_z.cfg).

However if I'm using the same file on the root of the config folder (with necessary changes to include right files) I don't get any error.

**Comment by Frix-x** [comment]
Oh indeed, I think you are using TAP ? If this is the case, it's definitely a bug that should be solved in the next release :)

**Comment by Frix-x** [comment]
Fixed in https://github.com/Frix-x/klippain/commit/670551ac077bf20addffb831938a8d12a7e7e1de

**Comment by 22MarioZ** [comment]
I need to reopen this ticket as the bug was re-introduced with 4.0.1. Can you fix it soon?

**Comment by 22MarioZ** [comment]
Ignore my previous comment...
