### ISSUE TITLE
Removing unnecessary toolhead movement?

### ISSUE THREAD

**Issue by Surion79** [Frix-x/klippain#187]
When meeting the requirements for not soaking the bed/chamber, the toolhead is still moved to the waiting point, instantly going for the next module. I'd rather skip movement if it is not required. Instead a PR, this as issue. It is at least required for bed and chamber soak.

**Comment by Frix-x** [comment]
This is done in https://github.com/Frix-x/klippain/commit/09b9a96a11cd7477eaf5d54f9ecfa5c763e5d576
