### ISSUE TITLE
Adding KNOMI screen compatibility

### ISSUE THREAD

**Issue by Surion79** [Frix-x/klippain#202]
WIP ⚠️
added a PR to KNOMI repo for better accesibility for status.
Current implementation does not work for printer with homing overrides.
If the change is accepted in KNOMI, I start to add the code for it in Klippain.

**Comment by Frix-x** [comment]
I'll close this PR as it look like there is nothing to be added to Klippain for now and it should just work.
There is still the macro addition problem, but it's a problem on the KNOMI side, not in Klippain.

We'll reopen this issue if it needs more work but I'm pretty sure it will be ok :)

**Comment by jace** [comment]
I just installed a Knomi 2 and it's stuck on the G28 macro override conflicting with `homing_override`. @Frix-x Knomi's requirements seem trivial enough to include support in Klippain. It just requires setting macro variables and doesn't look like it'll have any unwanted side effects even if always enabled.
