### ISSUE TITLE
Chamber heatsoak showing "incorrect" OK even when temperature is not met

### ISSUE THREAD

**Issue by Surion79** [Frix-x/klippain#210]
Just installed a chamber thermistor and it was strange that the temperature was showed as "OK" but it was not. There was no info like bed soak that the timer has passed. 
It should be a bit more precise about this.

**Comment by Benoitone** [comment]
Maybe the value of variable_print_default_chamber_max_heating_time: ?

**Comment by Surion79** [comment]
well, in my test it was only an OK, without reaching the time limit. there was no info about "maximum time elapsed" or something

**Comment by Frix-x** [comment]
If OK is printed in the console, it means that the chamber temperature is already above the temperature setpoint (set from the START_PRINT `CHAMBER` parameter or defaulting to `variable_print_default_chamber_max_heating_time`).

**Comment by Benoitone** [comment]
So maybe change the RESPOND MSG="Chamber temperature OK !"
To something like
RESPOND MSG="Chamber temperature OK or maxtime reached !" ?

**Comment by Frix-x** [comment]
I think Benoitone is right. I just understand the problem. We'll add something like that to the next version :)

**Comment by Surion79** [comment]
i would like to be more specific and not generic about what could have happened
