### ISSUE TITLE
Please implement adaptive purge

### ISSUE THREAD

**Issue by rugolini** [Frix-x/klippain#215]
The adaptive purge is a "all in one" (purge + prime line) procedure that allows us to save time on each print. Can you incorporate it to the print start and add an option for it?

**Comment by Surion79** [comment]
@rugolini Do you have a reference? A solution in a similar way like KAMP is already in v4 development branch in rigorous testing.

**Comment by rugolini** [comment]
Ah! Great to know that!

**Comment by Surion79** [comment]
It is even compatible with ERCF <3

**Comment by Frix-x** [comment]
Closing as Klippain v4 is merged and released :)
