### ISSUE TITLE
AXES_SHAPER_CALIBRATION output missing axis info

### ISSUE THREAD

**Issue by Surion79** [Frix-x/klippain#217]
When running AXES_SHAPER_CALIBRATION the output does not state which setting for X and which for Y. I ran it two times in a row and the output was apparently inverted. 

14:17 Recommended shaper is 3hump_ei @ 103.0 Hz
14:18 Recommended shaper is zv @ 37.6 Hz
14:51 Recommended shaper is zv @ 37.6 Hz
14:51 Recommended shaper is 3hump_ei @ 103.0 Hz

**Comment by Frix-x** [comment]
Problem is that I run the script in batch and doesn't know which file is done first. So I will not be able to do anything about that beside maybe hiding the results... You should look at the graphs directly instead
