### ISSUE TITLE
Adding optional Park in Pause

### ISSUE THREAD

**Issue by elpopo-eng** [Frix-x/klippain#221]
When we use the pause, the tool head doesn't move and therefore burns the surface where it stops.

I therefore propose to add an optional park in the pause

**Comment by Surion79** [comment]
Good point, need to check compatibility with ERCF and possible purge/clean before resume.

**Comment by elpopo-eng** [comment]
I already do this with the ercf and there's no problem.
But I don't think it's mandatory to add a clean purge and it would be dangerous to do a clean purge when you've already printed something. You could have a collision with the printed object on the bed.

**Comment by Benoitone** [comment]
In think I have put a park in pause when we rework ercf...

**Comment by Frix-x** [comment]
Yes this was reworked already in the develop branch :)

**Comment by elpopo-eng** [comment]
I see it and it works.
So i close this issue.
