### ISSUE TITLE
Load filament should "park" over purge bucket

### ISSUE THREAD

**Issue by rugolini** [Frix-x/klippain#224]
When changing filament (M600) the toolhead should execute the unload/load filament over the purge bucket, so the oozing filament end up in the bucket instead over the deck.

**Comment by Frix-x** [comment]
That's a thing I wanted to implement as well. I'll add it to the priority list when the v4 is released :)

**Comment by Frix-x** [comment]
This was done in 6cc5d8748dd718c0f07556fedf015ffba27bc3a0 (develop branch)
It's planned to be released to main soon :)
