### ISSUE TITLE
Reset hz_per_sec after using EXCITATE_AXIS_AT_FREQ 

### ISSUE THREAD

**Issue by Fragmon** [Frix-x/klippain#225]
If you use this macro it sets the hz_per_sec. After using this value is not reset. 

Problem: If you use normal ressonance test after that. This time value is used.

For example: It need 10s for each hz (1-133hz).

**Comment by Frix-x** [comment]
This is already done in the develop branch (that will be merged very soon to main). See commit c7d8b2b
