### ISSUE TITLE
Publish shaper calibration scripts as separate plugin?

### ISSUE THREAD

**Issue by thisiscam** [Frix-x/klippain#229]
Hi,

I wonder if you would consider publishing the shaper calibration scripts as separate klipper plugins? They look great and I think is a must have for most printers. But some users (like I) might not be able to make the full switch to klippain because our existing configs are too large to be ported easily..

Thank you

**Comment by Frix-x** [comment]
Hi,
Thanks for raising an issue about that.

In fact, I designed all the calibration macros (as the InputShaper automated workflow and scripts) as detached from the Klippain code. This means that you can already install them as standalone as a lot of people are already doing. The install documentation is here: https://github.com/Frix-x/klippain/blob/main/docs/features/is_workflow.md

**Comment by Surion79** [comment]
> Hi,
> 
> 
> 
> I wonder if you would consider publishing the shaper calibration scripts as separate klipper plugins? They look great and I think is a must have for most printers. But some users (like I) might not be able to make the full switch to klippain because our existing configs are too large to be ported easily..
> 
> 
> 
> Thank you

If you ever plan to migrate to Klippain, you could start by open an issue for a single feature request and it gets easier over time to migrate :-)

**Comment by thisiscam** [comment]
> Hi, Thanks for raising an issue about that.
> 
> In fact, I designed all the calibration macros (as the InputShaper automated workflow and scripts) as detached from the Klippain code. This means that you can already install them as standalone as a lot of people are already doing. The install documentation is here: https://github.com/Frix-x/klippain/blob/main/docs/features/is_workflow.md

Hi thanks! Yes, I found that documentation after posting this issue. You are right that manual installation might be fine. But, users installing these manually will not be able to catch any updates you push to these scripts in this repo. I would agree that these scripts seems fairly stable that maybe a separate repo is not necessary, though.
