### ISSUE TITLE
Default TMC2240 Extruder setting instantly goes for undervoltage

### ISSUE THREAD

**Issue by Surion79** [Frix-x/klippain#230]
My sb2240 has the issue that with the 'default' it runs 99% of the time. With the additional config it doesnt work.
I suggest putting the additional tmc2240 config as comment instead of uncommented.

**Comment by Frix-x** [comment]
Hi, yes you're right.
This need to be tweaked to every machine as the TMC2240 is way smarter that the other TMCs from Trinamics and allow deeper configurations but it is also much more sensitive to things like input voltage, etc... So it need to be configured carrefully.

FYI, there is currently some work done on this topic in the Voron Discord that will lead to some "auto-tuning" algorithms for all the TMCs drivers in Klipper. Please be patient :)
So I'll put this on hold for the moment while waiting for this
