### ISSUE TITLE
BIGTREETECH BTT Pi V1.2

### ISSUE THREAD

**Issue by jha03500** [Frix-x/klippain#232]
Bonjour, 

Klippain est il ou sera il compatible avec le BIGTREETECH BTT Pi V1.2 ?

Merci

**Comment by Frix-x** [comment]
> E.g. graph_vibrations.py has a changelog for being independant of "pi", but it is linked in line 217 as default.

Yes but it's not used. The Pi in the script is default if no parameter is sent to the script call. The thing (that is said in the changelog) is that now the script accept a parameter for that, and this is used also in the plot_graph.sh here (-k parameter):
https://github.com/Frix-x/klippain/blob/4baf0ea6aec60c3959693b95e531a336bea9a906/scripts/plot_graphs.sh#L139

So this is not a problem anymore and also work when the use is not pi :)

The only place where it's still needed and I can't use a generic like (`~/`) is in the shell_command. But this is not really a problem as it can be overriden very easily
https://github.com/Frix-x/klippain/blob/4baf0ea6aec60c3959693b95e531a336bea9a906/scripts/shell_commands.cfg#L4-L7

**Comment by Surion79** [comment]
@Frix-x i think the requester likes an answer 'en français' 😀

**Comment by jha03500** [comment]
Oui le français est ma langue, mais je peux faire l’effort 
Ma question est peut on installer klippain sur un BTT Pi V1.2 ? La procédure est compliquée ? 
Merci

**Comment by Surion79** [comment]
La procédure n'est pas compliquée.
BTT Klipper Pi 1.2 est lent. 
(Je parle un poco peu français)

**Comment by Frix-x** [comment]
Hello,

Oups, oui j'avais pas fait attention que c'était en Français ^^
Mais du coup Klippain est une configuration spéciale pour Klipper (c'est un équivalent au fichier `printer.cfg` que tu connais déjà surement). Donc cela veut dire que si Klipper fonctionne, Klippain aussi :)

**Comment by jha03500** [comment]
Merci,
Pour vos explications

**Comment by Frix-x** [comment]
Globalement oui, Klippain c'est ça :)

**Comment by jha03500** [comment]
Merci pour votre patience 😉
