### ISSUE TITLE
SB2209 with ADXL missing MCU_SPI2_CS

### ISSUE THREAD

**Issue by rugolini** [Frix-x/klippain#235]
When using [include config/mcu_definitions/toolhead/BTT_SB2209_v1.0.cfg]
Klipper cannot start stating error: "ADXL missing MCU_SPI2_CS"
no matter what ADXL I include:
[include config/hardware/accelerometers/adxl345_ebb.cfg] or
[include config/hardware/accelerometers/adxl345_sb2040.cfg]

is adxl345_sb2209.cfg missing or am I doing something wrong?

**Comment by Frix-x** [comment]
Hi, thanks for raising the issue. As discussed on Discord, it's a typo and changing `ADXL_CS=MCU_SPI2_CS` to `ADXL_CS=MCU_SPI2_NSS` solve your issue.

This was solved in this commit alongside some other minor modifications to the ADXL system (currently in the dev branch): 57ab6ed20a6b47619c4d37e5bf94ce67320ee964
