### ISSUE TITLE
[FR] Primeline as own macro with parameters

### ISSUE THREAD

**Issue by Surion79** [Frix-x/klippain#236]
I am currently trying to do some tests with multiple prime lines to see the different outcomes based on the tmc2240 extruder.
I wonder (thats why i open an issue instead of a PR) if it is possible to have the primeline function dedicated and having parameters to be called (e.g. individual start coordinates). The functionality is already used without direct parameters in the primeline module.
Idea is to cut this primeline out, make it independant and add parameters to it. It is then called also from the primeline module. so it is no breaking change.

Goal is to have it like the heatsoak modules, where this type of implementation has been already done.

**Comment by Frix-x** [comment]
Yes sure, I'll convert it quickly :)
