### ISSUE TITLE
BELTS_SHAPER_CALIBRATION & AXES_SHAPER_CALIBRATION = Unknown command

### ISSUE THREAD

**Issue by PigeonFX** [Frix-x/klippain#243]
Followed the Input Shaper workflow guide laid out in https://github.com/Frix-x/klippain/blob/main/docs/features/is_workflow.md  but both BELTS_SHAPER_CALIBRATION & AXES_SHAPER_CALIBRATION just throw up a Unknown command error.

**Comment by Surion79** [comment]
mmh, you included the macro file to your printer.cfg? You can look into klippy.log if you can find the command there. if not, the file is not included in printer.cfg

**Comment by Surion79** [comment]
![image](https://github.com/Frix-x/klippain/assets/102791900/a2f499c7-ba8d-4c33-8f12-56fde8e2e8db)
