### ISSUE TITLE
Filament Runout Sensor "pause_on_runout" functionality is disabled by default.

### ISSUE THREAD

**Issue by AzimuthHeavyIndustry** [Frix-x/klippain#252]
Currently the filament motion sensor has no functionality by default, even if it is uncommented in the most recent printer.cfg template to enable it.

![Screenshot 2023-07-04 223026](https://github.com/Frix-x/klippain/assets/111710251/1052da87-ef80-4509-bbee-571f5c84d96b)

pause_on_runout is set to false and no additional runout gcode is provided thereby defeating the functionality of the module.

**Comment by Frix-x** [comment]
This is solved in 46b240366d91aa123ef144f62f720c7fc19cad21 to be released soon :)
