### ISSUE TITLE
Missing [manual_mh_stepper selector_stepper] section in mmu_hardware.cfg (New HappyHare)

### ISSUE THREAD

**Issue by Fragmon** [Frix-x/klippain#280]
I have an error with the combination orbiter2 and mmu with the klippain config.
I use the this branch https://github.com/Frix-x/klippain/tree/new-ercf_HHv2

![image](https://github.com/Frix-x/klippain/assets/50713890/98e0ae4e-a292-495e-bf3a-db20e4ad86d7)
![image](https://github.com/Frix-x/klippain/assets/50713890/c55f9d94-9039-40f5-a7cd-32e373de539c)
![image](https://github.com/Frix-x/klippain/assets/50713890/45a60976-9f5f-47f3-a324-85d406243ca7)

@Benoitone 
[printer.txt](https://github.com/Frix-x/klippain/files/12306660/printer.txt)

I try to separate the mmu_*.cfg to each file. But i doesnt work too.

**Comment by Benoitone** [comment]
Can you post your klipper.log?

**Comment by Fragmon** [comment]
Problem is solved with update happy hare branch :-) thx @Benoitone
