### ISSUE TITLE
Request : add MCU BTT Octopus Max EZ

### ISSUE THREAD

**Issue by NanoMetere** [Frix-x/klippain#281]
builded a machine with octopus max ez, but no config for this, so i cooked some config in there.
yes. it was painful lol. but i hope nobody wants to got a pain from this.

im sure this will work fine, but check twice.

because of two types of probe pins exist, I wrote probe pins to bltouch header, not inductive probe pins.
and Motors and endstop numbers in manual starts with 1 not 0 but wrote starts with 0 so edit the number if needed.

[BTT_Octopus_MAX_EZ.txt](https://github.com/Frix-x/klippain/files/12327557/BTT_Octopus_MAX_EZ.txt)

    [board_pins mcu_manufacturer]

    aliases:
    MCU_MOTOR0_STEP=PC13   , MCU_MOTOR0_DIR=PC14   , MCU_MOTOR0_ENABLE=PE6   , MCU_MOTOR0_UART=PG14     ,
    MCU_MOTOR1_STEP=PE4    , MCU_MOTOR1_DIR=PE5    , MCU_MOTOR1_ENABLE=PE3   , MCU_MOTOR1_UART=PG13    ,
    MCU_MOTOR2_1_STEP=PE1 , MCU_MOTOR2_1_DIR=PE0  , MCU_MOTOR2_1_ENABLE=PE2  , MCU_MOTOR2_1_UART=PG12  ,
    MCU_MOTOR3_STEP=PB8    , MCU_MOTOR3_DIR=PB9    , MCU_MOTOR3_ENABLE=PB7    , MCU_MOTOR3_UART=PG11    ,
    MCU_MOTOR4_STEP=PB5    , MCU_MOTOR4_DIR=PB4   , MCU_MOTOR4_ENABLE=PB6    , MCU_MOTOR4_UART=PG10    ,
    MCU_MOTOR5_STEP=PG15   , MCU_MOTOR5_DIR=PB3    , MCU_MOTOR5_ENABLE=PD5    , MCU_MOTOR5_UART=PG9    ,
    MCU_MOTOR6_STEP=PD3    , MCU_MOTOR6_DIR=PD2    , MCU_MOTOR6_ENABLE=PD4    , MCU_MOTOR6_UART=PD7    ,
    MCU_MOTOR7_STEP=PA10    , MCU_MOTOR7_DIR=PA9   , MCU_MOTOR7_ENABLE=PA15    , MCU_MOTOR7_UART=PD6    ,
    MCU_MOTOR8_STEP=PD3    , MCU_MOTOR8_DIR=PD2    , MCU_MOTOR8_ENABLE=PD4    , MCU_MOTOR8_UART=PG8    ,
    MCU_MOTOR9_STEP=PA10    , MCU_MOTOR9_DIR=PA9   , MCU_MOTOR9_ENABLE=PA15    , MCU_MOTOR9_UART=PG7    ,

    MCU_STOP0=PF0  , MCU_STOP1=PF2  , MCU_STOP2=PF4 , MCU_STOP3=PF3 ,
    MCU_STOP4=PF1 , MCU_STOP5=PC15
    MCU_PROBE=PB15  ,
    MCU_SERVOS=PB14 ,

    MCU_HE0=PF6 , MCU_HE1=PA0 , MCU_HE2=PF9 , MCU_HE3=PF7 ,

    MCU_BED0=PF5 ,

    MCU_TB=PB1 ,
    MCU_T0=PB0 , MCU_T1=PC5 , MCU_T2=PC4 , MCU_T3=PA7 ,

    MCU_FAN0=PA6 , MCU_FAN1=PA5 , MCU_FAN2=PA4 , MCU_FAN3=PA3 ,
    MCU_FAN4=PA1 , MCU_FAN4_TACH=PC3 ,
    MCU_FAN5=PF8 , MCU_FAN5_TACH=PC1 ,
    MCU_FAN6=PA2 , MCU_FAN6_TACH=PC2 ,

    MCU_NEOPIXEL=PE10  ,
    MCU_NEOPIXEL2=PE9  ,
    MCU_PS_ON=PF13    ,
    MCU_POWER_DET=PF12 ,

    # EXP1 header
    EXP1_1=PG2   , EXP1_2=PD15   ,
    EXP1_3=PD14   , EXP1_4=PD13  ,
    EXP1_5=PD12  , EXP1_6=PD11  ,  # Slot in the socket on this side
    EXP1_7=PD10  , EXP1_8=PE15  ,
    EXP1_9=<GND> , EXP1_10=<5V> ,

    # EXP2 header
    EXP2_1=PE13   , EXP2_2=PE12   ,
    EXP2_3=PG5   , EXP2_4=PE11   ,
    EXP2_5=PG4   , EXP2_6=PE14   ,  # Slot in the socket on this side
    EXP2_7=PG3  , EXP2_8=<RST> ,
    EXP2_9=<GND> , EXP2_10=<NC> ,

**Comment by Frix-x** [comment]
Hello!

Thanks for your issue and info. I'm sorry about that you had to take this time to find out the pinout as it is already implemented in the develop branch since a couple of weeks by this commit: https://github.com/Frix-x/klippain/commit/4f692d40472d8521a20cf8464ec6be950561afeb

This is planned to be released publicly in the main branch very soon!
If you find out a mistake or miss something in the one already implemented in Klippain, please let me know to correct it before the release :)
