### ISSUE TITLE
Mismatch in SKR Pico mcu_definition and user_template files

### ISSUE THREAD

**Issue by NoSoucy10** [Frix-x/klippain#283]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.1.0-0-g5e24c04f and earlier

### Describe the bug and expected behavior

There's a mismatch in the extruder motor pins' names between the SKR Pico mcu_definition file and the user_template that's used to generate the mcu.cfg file.

In the definition file, the extruder motor pins are named MCU_E0_* but in the template it uses MCU_E_*

user_template:
![image](https://github.com/Frix-x/klippain/assets/5062956/f1a00376-4ceb-4bcb-840c-55f733fadbd9)

mcu_definition:
![image](https://github.com/Frix-x/klippain/assets/5062956/02eb8ce5-77b7-4e12-9acd-6533fde6f8cf)

This causes an error with klipper that can't find the requested pins.
![image](https://github.com/Frix-x/klippain/assets/5062956/2980763b-c724-49b6-b4eb-b639c1ff233b)

Renaming them to the correct ones in my mcu.cfg fixed the error.

I suggest renaming the ones in the SKR Pico user_template file to the ones in the mcu_definition file.
Sorry for not just making a PR for this simple issue, I don't really know how to participate in a github repo.

Midhy

**Comment by Frix-x** [comment]
Thanks for catching this!
I'll fix it in the next release for everyone :)

**Comment by Surion79** [comment]
Oooh, nice fiend from me too!
I wonder why this never came up on my pico. Need to check after move

**Comment by Frix-x** [comment]
This should be fixed in 00ec18e8e89e5edb01f8351130d23c03b2f149c5 to be released in the next version :)
