### ISSUE TITLE
Add CUSTOM_MODULE to END_PRINT

### ISSUE THREAD

**Issue by AMFkuna** [Frix-x/klippain#288]
### Describe the feature or hardware support you'd like

Hi 
Can you please add CUSTOM_MODULE to END_PRINT macro like in START_PRINT macro? I am using a clean brush which is located on the gantry and I would like to use it at the end of the print. Thanks

**Comment by Frix-x** [comment]
Hello, thanks for the suggestion!

However i'm unsure about the usefullness of this: indeed the custom modules in the start print routine are here to be able to change the order of actions and/or add custom actions to a pretty complex macro.
In the case of the print end, the macro is pretty light and you should just override it and add your needed gcode lines directly

**Comment by AMFkuna** [comment]
Hi,
You are right, it is simply to override this macro.

I found duplicity in END_PRINT macro variables definition
![Snímek obrazovky 2023-09-04 v 21 26 04](https://github.com/Frix-x/klippain/assets/17743216/7aeaf7c3-d94f-4d3e-a581-f32c25cf907d)

**Comment by Benoitone** [comment]
Yes, for the duplicate... it's only in the Happy Hare branch that's in work in progress, in parallel of Happy Hare v2
