### ISSUE TITLE
Filter stop during next print

### ISSUE THREAD

**Issue by AMFkuna** [Frix-x/klippain#295]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.1.1

### Describe the bug and expected behavior

Hi
After printing is finished, the filter runs according to the set time. If I start repeated printing at this time, the filter runs according to the START_PRINT macro, but it turns off after the previous run-down timeout.

**Comment by Frix-x** [comment]
Hey thanks for raising this issue. This is something I already detected. It should be a quick fix. I'll add it to the next version :)

**Comment by Frix-x** [comment]
This is now fixed in the develop branch (commit 82e3ba8209944b1194a77355220d63c459ca86f3) and will be released in the next version :)
