### ISSUE TITLE
Filament swith sensor doesn't work

### ISSUE THREAD

**Issue by Daedy80** [Frix-x/klippain#304]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.1.1-0-g0122cd35

### Describe the bug and expected behavior

Hello,

After I uncomment the [include config/hardware/filament_sensors/switch_sensor.cfg] I have the following error 
![image](https://github.com/Frix-x/klippain/assets/7904140/ef150fec-1fe2-4ef1-ad83-09c3a47c674a)

I comment the line in printer.cfg and copy the content of the /config/config/hardware/filament_sensors/switch_sensor.cfg in overrides without the line "extruder: extruder" and it works.

**Comment by Frix-x** [comment]
Thanks for raising this issue.
This is already solved in the develop branch to be released soon :)
