### ISSUE TITLE
Klipper Startup Error "variable_bed_mesh_profile" on Python2

### ISSUE THREAD

**Issue by julianschweizer** [Frix-x/klippain#346]
### Klippain branch

- [X] I confirm using the main branch

### Version

4.2.0

### Describe the bug and expected behavior

Installed V4.2.0 today from scratch. 

Following Error:

```
Option 'variable_bed_mesh_profile' in section 'gcode_macro START_PRINT' is not a valid literal: unexpected EOF while parsing (<unknown>, line 0)

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted
```

**Comment by Surion79** [comment]
Could you add the call in your slicer settings? Or is it crashing  when klipper is starting up?
How do you define from scratch? Can you explain which settings/files you carried over? Some settings in the files are not looking for 'from scratch'

**Comment by Surion79** [comment]
somehow this is strange. the main branch of klippain has 
`variable_bed_mesh_profile =  ""`

but your config only
`variable_bed_mesh_profile = `

can you please verify? my installation works.

**Comment by Surion79** [comment]
Please provide your used klipper version and the slicer section for start print. 
What you linked would mean that everyone must have this error, but i don't have it.

**Comment by Surion79** [comment]
Still wondering, why you have the issue and apparently no one else. 🤔
For me the printer boots up, and we have a couple users running on dev branch to test these changes. 

But i have an idea to implement which might correct your issue also.

**Comment by ndanyluk** [comment]
Just wanted to add that I'm seeing this on an upgrade from 4.1.1 to 4.2.0 as well.  This is on Python 2.7.18

**Comment by ndanyluk** [comment]
FYI for those not using KIAUH, here are the steps per one of the klipper team members (I think): https://klipper.discourse.group/t/process-for-migrating-to-python3/5292/3

They seem pretty combative, but given Debian is finally moving away from packaging Python2 at all, I think Python3 may start to become the default.

**Comment by ndanyluk** [comment]
@Frix-x @Surion79 just want to confirm that migrating up to Python 3 solved this for me.  Also note that you need to install numpy for Python3 as well (last post in the Klipper thread above)

**Comment by Frix-x** [comment]
Ok so this confirm my hypothesis.
As Python3 is now the default, I'll not merge the PR as there is no need to absolutely keep Python2 compatibility in Klippain and we should rather focus on new features :)
