### ISSUE TITLE
Bug:  pinname typo in BTT_Manta_M8P_v2.0.cfg

### ISSUE THREAD

**Issue by Awakatanka** [Frix-x/klippain#352]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.2.0-2-g2e0f44da

### Describe the bug and expected behavior

There is a typo with the pin name. 

MCU_M3_STEP=BP8

This must be MCU_M3_STEP=PB8

Klipper reports: ERROR

Pin 'BP8' is not a valid pin name on mcu 'mcu'

**Comment by dhazelett** [comment]
sorry about that, I've got a PR up to fix that!

**Comment by Frix-x** [comment]
Good catch! And thank you @dhazelett for your reactivity :)
I'll merge the PR!
