### ISSUE TITLE
Pinname typo in BTT_MMB-CAN_v1.0.cfg

### ISSUE THREAD

**Issue by billys09** [Frix-x/klippain#353]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.2.0-149-g12837608

### Describe the bug and expected behavior

MCU_STP8 is used twice in the MCU stop definitions (MCU_STP8=PB12 , MCU_STP8=PB11). The second one should be MCU_STP9.

**Comment by Surion79** [comment]
I don't see it. no commit had this collision
