### ISSUE TITLE
Support for Filamentrix 

### ISSUE THREAD

**Issue by GlnSevi** [Frix-x/klippain#364]
### Describe the feature or hardware support you'd like

Hey,

I have problems to perform a filament cut. It always performs Tip Forming instead. I have another machine were Filamentrix runs smoothly. Can u implement it in your macros
Have a great day 😊

**Comment by Surion79** [comment]
For that we need more information.
Probably sonething overwrites an exisiting custom macro.
We can't work against custom macros. Can you add your klippy log?

**Comment by Frix-x** [comment]
I think this is probably not needed as it's already supported directly in HappyHare.
But I could miss something...

@Benoitone, do you have an idea about this?

**Comment by Surion79** [comment]
i think his issue is that the machine is doing something different when using the function. so i think it is more a macro collision than a "feature request"
