### ISSUE TITLE
Manta M8P v2.0 Fan 5 and FAN6 pins incorrect

### ISSUE THREAD

**Issue by kurtblah** [Frix-x/klippain#366]
### Klippain branch

- [x] I confirm using the main branch

### Version

v4.2.0-5-g6692712b

### Describe the bug and expected behavior

The  pin and the tach-pin assignments are swapped for FAN5 and FAN6.
 
[https://github.com/bigtreetech/Manta-M8P/blob/master/V2.0/Firmware/generic-bigtreetech-manta-m8p-V2_0.cfg](url) line 145

**Comment by Frix-x** [comment]
Good catch! I've fixed it in the last commit
