### ISSUE TITLE
Sensorless homing current and percentages consideration 

### ISSUE THREAD

**Issue by EricZimmerman** [Frix-x/klippain#378]
### Klippain branch

- [X] I confirm using the main branch

### Version

na

### Describe the bug and expected behavior

using a percentage of run current may be a bad idea as changing run current will then affect the homing sensitivity.

consider allowing for a set homing current to be used, vs a % of run current, i would think 0.49 would work for everyone, always, and its just a matter of finding the driver value that works at this current.

**Comment by Frix-x** [comment]
Thanks for this issue.

As discussed on Discord, this is just to be able to adapt to all kind of motors without any problem if the user let a default value in the variables.cfg. Percentage always works and avoid burning drivers or questions about why the motors are not moving (in case of a too low default value). Also, 75% is what is generally advised as a starting point in the TMC drivers documentation.

So while I want to keep this percentage value, I totally understand and agree with your point. So I'll add a small comment in the variables.cfg file to say it and avoid confusion.

**Comment by Surion79** [comment]
What about adding some options to have expert users set their own currents directly instead of a percentage? The percentage could work as a warning or plausability check about configured value

**Comment by EricZimmerman** [comment]
i can confirm the current approach works awesome. Nothing to see here...
