### ISSUE TITLE
Idle timeout tweak

### ISSUE THREAD

**Issue by EricZimmerman** [Frix-x/klippain#384]
### Describe the feature or hardware support you'd like

Add a note on idle timeout, so people know it happened

### Additional context or information

```
[idle_timeout]
timeout: 7200
gcode:
    RESPOND MSG="Idle timeout reached"
```

**Comment by EricZimmerman** [comment]
do you prefer issues or would you rather me do PRs?

**Comment by Surion79** [comment]
i do prefer issues, so it is easier to do changes for integration to Klippain. Some PRs tend to stale when changes are requested and never done.
But the quality is good. snippets of source code and some description i prefer than just descriptive text

**Comment by EricZimmerman** [comment]
ok, i can do that. fast enough turn around! hehe

**Comment by Surion79** [comment]
i know you can do that :) I am thinking about adding the repo saving of the manual settings you provided in this

**Comment by EricZimmerman** [comment]
I bumped my timeout too so I could hear soak for an hour on the 2.4

**Comment by Benoitone** [comment]
@Surion79 @EricZimmerman do you know if there is a way to tweak timeout time without having to restart? For my exemple, I sometimes use my enclosure to dry my spool @50degres and I set timeout to 18000!!!

**Comment by Surion79** [comment]
maybe with a delayed gcode command to "emulate" non idle?

**Comment by EricZimmerman** [comment]
SET_IDLE_TIMEOUT i believe

**Comment by Benoitone** [comment]
> SET_IDLE_TIMEOUT i believe

THANKS 🙏🏻
