### ISSUE TITLE
Support for SET_PRINT_STATS_INFO in start_print.cfg

### ISSUE THREAD

**Issue by dpeart** [Frix-x/klippain#387]
### Describe the feature or hardware support you'd like

I like to have the current layer updated in mainsail.  To do this you have to set the max layer count.  Previously I have set this in the slicers START_PRINT custom gcode: START_PRINT LAYERS={total_layer_count} (i.e. Prusa)

Then in my start_print macro I would issue the command: SET_PRINT_STATS_INFO total_layer=LAYERS

This allows me to issue a: SET_PRINT_STATS_INFO CURRENT_LAYER={layer_num + 1}
in the after layer change G-code section of the slicer and get mainsail to update the current layer count.  

It would be nice to be able to support the setting of the total_layer_count from the slicer into mainsail in the start_print.cfg.

thanks
david

**Comment by Benoitone** [comment]
Hello, to have information on the total number of layers or the current layer I don't think there is any other solution than to use the command in the slicer. This is a bit like the idea I had to turn off the lighting from a certain layer height [Here](https://github.com/Frix-x/klippain/pull/204). As at the moment klipper is not able to automatically return this information independently, it is better to use the layer parameters of the slicer with for example:
in the start gcode of the slicer
```
SET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count]
```
and;
```
SET_PRINT_STATS_INFO CURRENT_LAYER={layer_num}
```
at layer change.

Afterwards it is what you want to do with these values ​​which could be implemented in klippain

**Comment by dpeart** [comment]
Correct, I just was asking for the setting the TOTAL_LAYER to be included in the start_print.cfg.  It is always required and can be handled in the same way as we do`    # Set the variables to be used in all the modules based on the slicer parameters
    SET_GCODE_VARIABLE MACRO=START_PRINT VARIABLE=bed_temp VALUE={BED_TEMP}
    SET_GCODE_VARIABLE MACRO=START_PRINT VARIABLE=extruder_temp VALUE={EXTRUDER_TEMP}
    SET_GCODE_VARIABLE MACRO=START_PRINT VARIABLE=soak VALUE={SOAK}
    SET_GCODE_VARIABLE MACRO=START_PRINT VARIABLE=chamber_temp VALUE={CHAMBER_TEMP}
    SET_GCODE_VARIABLE MACRO=START_PRINT VARIABLE=chamber_maxtime VALUE={CHAMBER_MAXTIME}
    SET_GCODE_VARIABLE MACRO=START_PRINT VARIABLE=initial_tool VALUE={INITIAL_TOOL}
    SET_GCODE_VARIABLE MACRO=START_PRINT VARIABLE=material VALUE='"{MATERIAL}"'
    SET_GCODE_VARIABLE MACRO=START_PRINT VARIABLE=fl_size VALUE='"{FL_SIZE}"'
    SET_GCODE_VARIABLE MACRO=START_PRINT VARIABLE=bed_mesh_profile VALUE='"{BED_MESH_PROFILE}"'`

**Comment by Surion79** [comment]
what would be a default value for total_layer_acount if it is not set via parameters?
i see the potential for future stats and calculations for it within klippain. 
But still not sure what it means to have it not set and using a default of 0 or -1 might create issues.

**Comment by dpeart** [comment]
If the value isn't set in the START_PRINT section of the slicer, don't do anything.  It appears klipper defaults to 0, disabling the feature.

**Comment by Frix-x** [comment]
I just pushed an update to the draft PR of Surion. Let me know if it's ok for you this way and I'll merge :)
If it's not included, nothing is done to avoid breaking stuff. If you specify it, then it's applied in the Klipper stats but also stocked in the START_PRINT variables to be used later on in a custom module if needed :)

**Comment by Frix-x** [comment]
Closing since it was merged to develop :)
