### ISSUE TITLE
Issue with Flow Stability on Voron Trident When Printing Small and Complex First Layers

### ISSUE THREAD

**Issue by liustar1989** [Frix-x/klippain#395]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.2.0

### Describe the bug and expected behavior

I'm encountering an issue with my Voron Trident printer, specifically when printing the first layer of small and complex parts. The problem manifests as a gradually decreasing and unstable flow rate. After troubleshooting all possible causes, I've narrowed it down to an issue with the Klipper configuration.

When I use the original configuration, the flow rate is normal (as shown in Image 1). However, when I switch to using Klippain, the flow rate becomes abnormal (as demonstrated in Image 2 3).

Below are my configuration details. In addition to these, I have also modified the /config/software/z_calibration.cfg file in Klippain and added two files: /config/mcu_definitions/toolhead/EZ36.cfg and /config/hardware/accelerometers/adxl345_eztb36.cfg. Additionally, I included 'autotune_tmc'...
![微信图片_20231214141016](https://github.com/Frix-x/klippain/assets/88183374/2b659aaf-4faa-4069-aa2b-83400d56d56b)
![微信图片_20231214141029](https://github.com/Frix-x/klippain/assets/88183374/b93e10f5-3b91-41dc-ba86-64d876d07188)
![微信图片_20231214141034](https://github.com/Frix-x/klippain/assets/88183374/be9c55c4-f1eb-4c91-8f4d-f5a5950bad2d)

### Additional information and klippy.log

[klippain.zip](https://github.com/Frix-x/klippain/files/13669412/klippain.zip)
[klippy.log](https://github.com/Frix-x/klippain/files/13669418/klippy.log)

**Comment by Surion79** [comment]
is it possible to provide the full set of your mentioned "default config", the gcode file and your complete "klippain config"? the only thing i would compare would be some stuff like rotation distance or similar. if gcode is both the same, the are only little stuff that can have an impact (rotation distance, currents etc)

**Comment by liustar1989** [comment]
Klippain.zip is my complete Klippain configuration, and 1.zip is the configuration I used for successful prints. The rotation_distance settings are consistent in both. The G-code file F1_2023_Kit_Card_PLA_1h2m.gcode within 1.zip was sliced using Orca, and ss_F1_2023_Kit_Card.gcode was sliced using SuperSlicer.

Image 1 shows the print result of F1_2023_Kit_Card_PLA_1h2m.gcode using the configuration from 1.zip. Image 2 displays the print using the Klippain configuration for the same G-code file. Image 3 is the result of printing ss_F1_2023_Kit_Card.gcode with the Klippain configuration.

Since this issue only occurs while printing small and complex models, with the first layer printing normally and the problem not becoming apparent until partway through the print, particularly when the outer walls start showing noticeably thinner lines, I suspect that one of the issues might be related to the Z-axis height increasing, insufficient extrusion, or a clogged nozzle.

I'm wondering if this could be due to a specific parameter causing an overload on the Z or E motors, or possibly a failure in the bed mesh, especially when printing complex models.
[klippain.zip](https://github.com/Frix-x/klippain/files/13669412/klippain.zip)
[1.zip](https://github.com/Frix-x/klippain/files/13679640/1.zip)
![123](https://github.com/Frix-x/klippain/assets/88183374/c7a5e10e-d3e9-4183-a36b-0e7fb1198484)

![323](https://github.com/Frix-x/klippain/assets/88183374/d14f57bf-95fb-44d0-b4ec-19f1255c40c6)

**Comment by liustar1989** [comment]
> is it possible to provide the full set of your mentioned "default config", the gcode file and your complete "klippain config"? the only thing i would compare would be some stuff like rotation distance or similar. if gcode is both the same, the are only little stuff that can have an impact (rotation distance, currents etc)

Klippain.zip is my complete Klippain configuration, and 1.zip is the configuration I used for successful prints. The rotation_distance settings are consistent in both. The G-code file F1_2023_Kit_Card_PLA_1h2m.gcode within 1.zip was sliced using Orca, and ss_F1_2023_Kit_Card.gcode was sliced using SuperSlicer.

Image 1 shows the print result of F1_2023_Kit_Card_PLA_1h2m.gcode using the configuration from 1.zip. Image 2 displays the print using the Klippain configuration for the same G-code file. Image 3 is the result of printing ss_F1_2023_Kit_Card.gcode with the Klippain configuration.

Since this issue only occurs while printing small and complex models, with the first layer printing normally and the problem not becoming apparent until partway through the print, particularly when the outer walls start showing noticeably thinner lines, I suspect that one of the issues might be related to the Z-axis height increasing, insufficient extrusion, or a clogged nozzle.

I'm wondering if this could be due to a specific parameter causing an overload on the Z or E motors, or possibly a failure in the bed mesh, especially when printing complex models.
[klippain.zip](https://github.com/Frix-x/klippain/files/13669412/klippain.zip)
[1.zip](https://github.com/Frix-x/klippain/files/13679640/1.zip)
![123](https://github.com/Frix-x/klippain/assets/88183374/c7a5e10e-d3e9-4183-a36b-0e7fb1198484)

![323](https://github.com/Frix-x/klippain/assets/88183374/d14f57bf-95fb-44d0-b4ec-19f1255c40c6)

**Comment by Surion79** [comment]
wait, you used different slicers and different gcode files to compare different printer configurations?
In the name of process of elimination, please...
1. Create a single gcode file where you know that there is a different print quality when printing with different configurations
2. Use the file mentioned in 1 to print the file with your printer with your "own" configuration
3. Use the file mentioned in 1 to print the file with your printer with your "klippain" configuration.
4. Round up the single gcode file, the klippy.log of your own config renaming it to "klippy_ownConfig.log" and a klippain klippy.log renamed to "klippy_klippain.log" and zip these and attach to this issue.
5. Make pictures of your print issues and mark them

I think this is the only way to get a hold on this reported issue
