### ISSUE TITLE
Extruder add printing temperature but Klippain still goes to save temperature

### ISSUE THREAD

**Issue by roykrikke** [Frix-x/klippain#421]
### Describe the feature or hardware support you'd like

If I preheat my extruder. Klippain is not checking if the extruder is already add the needed printing temperature. I don't know if there's a reason for that. I think a check can be built in to ensure that the temperature does not first return to extruder safe temperature aka variable_safe_extruder_temp from variables.cfg.

**Comment by Surion79** [comment]
Can you explain a bit more? Sounds like an issue to check.
Klippy log until error (extruder not at temp) would be good atarting point

**Comment by roykrikke** [comment]
I think this image shows what I explained. Around 15:36 I started the print. Around 15:30 I started the preheat, but manual.
![Screenshot from 2023-12-23 15-42-34](https://github.com/Frix-x/klippain/assets/37672838/ca4eeb82-5d10-4385-a647-63fce4e9091e)

**Comment by Surion79** [comment]
why do you preheat your extruder?

**Comment by roykrikke** [comment]
I just this time preheat manual for no good reason. I just noticed that "klippain" first went back to safe temp on the extruder. I don't think that's necessary. Klippain makes the assumption that the extruder is cold. Which might also make sense, but if it's already on temperature. My thought was: why cool down first.

**Comment by EricZimmerman** [comment]
You need to if using tap but not necessarily for other probes

**Comment by roykrikke** [comment]
> You need to if using tap but not necessarily for other probes

That not the point. The point is just check if extruder is hot and don't cool down if not needed. Under any condition.

**Comment by EricZimmerman** [comment]
It is the point. Tap has to be taken into consideration else it probes the bed too hot. 

For non tap sure those checks can be added but that is hardly under any condition

**Comment by roykrikke** [comment]
> It is the point. Tap has to be taken into consideration else it probes the bed too hot.
> 
> For non tap sure those checks can be added but that is hardly under any condition

Oke now I get your point. I not using a tab and therefor did not think about this.

**Comment by Surion79** [comment]
i close the issue since it is cleard in my understanding. Nothing to be done
