### ISSUE TITLE
overides misspelled

### ISSUE THREAD

**Issue by EricZimmerman** [Frix-x/klippain#422]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.2.0-14-g32344ff2

### Describe the bug and expected behavior

![image](https://github.com/Frix-x/klippain/assets/4265254/ed90c138-2cfa-43d5-a3bb-fbddda386eed)

I checked for other uses of 'overides' but everywhere else i saw said overrides

### Additional information and klippy.log

nothing critical but wanted to log it as i am reconfiguring printer

**Comment by Surion79** [comment]
i created a PR. please have a look :)
