### ISSUE TITLE
mainboard Mellow Fly Super-8 support

### ISSUE THREAD

**Issue by hurr1k4ne** [Frix-x/klippain#451]
### Describe the feature or hardware support you'd like

I'd love to see support for Fly Super-8 Board from mellow store.
I have a non pro V1.0
There are 4 Board Revision out on the market

**Comment by Benoitone** [comment]
can you check this PR #463 ?

**Comment by RichardTHF** [comment]
I checked over the pins they look good! Hopefully they will approve it for use with Klippain!

**Comment by Frix-x** [comment]
This was merged in the develop branch and will be available in the next release (in a day or two).
