### ISSUE TITLE
BTT Kraken support

### ISSUE THREAD

**Issue by DaWingla** [Frix-x/klippain#457]
### Describe the feature or hardware support you'd like

is the support of the BTT Kraken planed??

**Comment by Phantastic1** [comment]
following... I'm currently running a BTT Kraken for my MCU and would like to see a configuration for this MCU

**Comment by Benoitone** [comment]
> following... I'm currently running a BTT Kraken for my MCU and would like to see a configuration for this MCU

On which printer?

**Comment by DaWingla** [comment]
I run it in a voron 2.4

**Comment by DaWingla** [comment]
S1 and s2 are a and b and s5 6 7 and 8 are there z drives. Like the ldo 2.4 config.

**Comment by DaWingla** [comment]
I made an rough printer.cfg so that the printer works.larer I could post it

**Comment by Benoitone** [comment]
ok...
can you check #476 ?

**Comment by DaWingla** [comment]
Ohh cool thank you .

**Comment by Frix-x** [comment]
PR merged in develop. It will be available on the next release :)
