### ISSUE TITLE
Klippain Startup does not work/trigger

### ISSUE THREAD

**Issue by Surion79** [Frix-x/klippain#461]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.2.0-54

### Describe the bug and expected behavior

Klippain start macro does not execute. not sure if this is a klipper issue

**Comment by Frix-x** [comment]
This was fixed in [0ecc550](https://github.com/Frix-x/klippain/commit/0ecc550a594b38fb9530bbd33858169937decbe1)
