### ISSUE TITLE
to be add in `FixMmuErrorOnPrintStart` branch

### ISSUE THREAD

**Issue by Benoitone** [Frix-x/klippain#479]
I think a fix must be add here too...
Maybe like this?
https://github.com/Frix-x/klippain/blob/a1330743e6469f08db3fc59c2e3e59cd2a7bbb31/macros/base/cancel_print.cfg#L9
```suggestion
    {% set mmu_unload_on_cancel_print = printer["gcode_macro _USER_VARIABLES"].mmu_unload_on_cancel_print|default(0) %}
```

**Comment by Surion79** [comment]
i think Klipper only errors out when using `default` on non existing variables
