### ISSUE TITLE
Incorrect endstop pin definition for in config/mcu_definitions/mmu/BTT_MMB_CAN_v1.0.cfg (develop branch)

### ISSUE THREAD

**Issue by claudioguareschi** [Frix-x/klippain#485]
### Klippain branch

- [X] I confirm using the main branch

### Version

develop branch

### Describe the bug and expected behavior

Fix, sorry for filing this bug report but it is a quick fix and I didn't want to submit a pull request for something this trivial. I just completed an ERCF and troubleshooting I noticed the pin definitions for the endstops for the BTT MMB CAN were incorrect in the develop branch I am using while playing with led effects.

I am pasting the correct pin definitions that I have tested to be working correctly and in line with the BTT definitions.
You can cut and paste it in the develop branch if you like.

========================================
config/mcu_definitions/mmu/BTT_MMB_CAN_v1.0.cfg
========================================

[board_pins mmu_manufacturer]
mcu: mmu
aliases:
    MCU_M1_STEP=PB15   , MCU_M1_DIR=PB14   , MCU_M1_EN=PA8    , MCU_M1_UART=PA10   , # MCU_M1_DIAG=PA3   ,
    MCU_M2_STEP=PD2    , MCU_M2_DIR=PB13   , MCU_M2_EN=PD1    , MCU_M2_UART=PC7    , # MCU_M2_DIAG=PA4   ,
    MCU_M3_STEP=PD0    , MCU_M3_DIR=PD3    , MCU_M3_EN=PA15   , MCU_M3_UART=PC6    , MCU_M3_DIAG=PB9   ,
    MCU_M4_STEP=PB6    , MCU_M4_DIR=PB7    , MCU_M4_EN=PB5    , MCU_M4_UART=PA9    , # MCU_M4_DIAG=PB8   ,

    MCU_MISO=PA6  , MCU_SCK=PA5  , MCU_MOSI=PA7  ,

    MCU_STP1=PA3 , MCU_STP2=PA4  , MCU_STP3=PB9  , # Shared with Steppers Diag pins  1-2-4 so it's better to use STP 4-11 for others servos/sensors
    MCU_STP4=PB8 , MCU_STP5=PC15 , MCU_STP6=PC13 , MCU_STP7=PC14 , MCU_STP8=PB12 , MCU_STP9=PB11 , MCU_STP10=PB10 , MCU_STP11=PB2 ,

    MCU_MOT=PA0      ,
    MCU_SENSOR=PA1   ,
    MCU_RGB=PA2      ,

    ## I2C header
    MCU_I2C_SDA=PB4  , MCU_I2C_SCL=PB3  ,

    ## SWD header
    MCU_SWD_PA14=PA14 , MCU_SWD_PA13=PA13 ,

======================================

I am attaching the BTT MMU pinout picture for reference
![MMB CAN V1 0-Pin](https://github.com/Frix-x/klippain/assets/33001685/00300881-e633-4237-9ad7-2dcb83479417)

**Comment by Benoitone** [comment]
corrections in #486
