### ISSUE TITLE
Wrong probe pin for BTT_SB2209_RP2040_v1.0 when using Voron Tap 

### ISSUE THREAD

**Issue by faelenor** [Frix-x/klippain#506]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.2.0-24-g4dd8a613

### Describe the bug and expected behavior

The PROBE_INPUT pin is set to MCU_IND_FAN, but it should be MCU_PROBE2 when using Voron Tap. See:

https://github.com/Frix-x/klippain/blob/main/user_templates/mcu_defaults/toolhead/BTT_SB2209_RP2040_v1.0.cfg#L22

**Comment by Surion79** [comment]
fixed, thanks for the info

**Comment by Frix-x** [comment]
And it's merged in develop
