### ISSUE TITLE
Typo in config/mcu_definitions/toolhead/LDO_Nitehawk-SB_v1.0.cfg

### ISSUE THREAD

**Issue by akashrpatel** [Frix-x/klippain#510]
### Klippain branch

- [X] I confirm using the main branch

### Version

4.3

### Describe the bug and expected behavior

MCU_RGB=gpio17 it should be MCU_RGB=gpio7

**Comment by Frix-x** [comment]
Thanks for the info. This is fixed in the latest commit from the main branch :)
