### ISSUE TITLE
Select the Fysetc ERB in the installer, but in the MCU.cfg the Mellow FlyERCF is inserted.

### ISSUE THREAD

**Issue by DaWingla** [Frix-x/klippain#518]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.3.0-3-g9cf27c3b

### Describe the bug and expected behavior

As i the titel descripted i installed the Fysetc ERB and in the MCU.CFG as MMU MCU is the Mellow Fly

**Comment by DaWingla** [comment]
![Screenshot 2024-02-29 194242](https://github.com/Frix-x/klippain/assets/52883784/06e51282-eee6-4fdd-848a-c3727ff9bac4)
![Screenshot 2024-02-29 194612](https://github.com/Frix-x/klippain/assets/52883784/55b1ff2c-187f-48cb-9e2f-5a9a2da81936)

**Comment by Benoitone** [comment]
you’re right 👍
#519
