### ISSUE TITLE
Add the variable adaptive_primeline to variables.cfg  that can be overriden in start_print

### ISSUE THREAD

**Issue by tsk-2222** [Frix-x/klippain#520]
### Describe the feature or hardware support you'd like

The latest version of klippain defaults to using adaptive primeline. Currently this can be overridden by using ADAPTIVE_PRIMELINE=0 on the start_print line.

I think it would be a good idea to add it as a variable in variables.cfg and then have the start_print macro default to using that variable.

It's an easy patch and I'lll submit a PR myself when I get back at my printer in 4 days ...unless someone beats me to it.

**Comment by Surion79** [comment]
added a PR. please take a look

**Comment by Surion79** [comment]
not yet completed. will be closed when merged
