### ISSUE TITLE
Failed to detect git branch & shake&tune fails to install

### ISSUE THREAD

**Issue by Svennixx** [Frix-x/klippain#526]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.3.0

### Describe the bug and expected behavior

I have installed a fresh klipper on my new raspberry pi 4, installed klippain without issues really. Everything works except for the moonraker updates and shake&tune (even though it is installed according to the install.sh).
![image](https://github.com/Frix-x/klippain/assets/5203461/c242eb42-f39b-49fa-828c-84172fdb08b6)
![image](https://github.com/Frix-x/klippain/assets/5203461/803d0007-20f9-4f43-9c95-2950ba234006)
![image](https://github.com/Frix-x/klippain/assets/5203461/fcde123d-2f74-4bd7-a852-109a97f21287)

### Additional information and klippy.log

[moonraker.log](https://github.com/Frix-x/klippain/files/14477943/moonraker.log)

[klippy (6).log](https://github.com/Frix-x/klippain/files/14477931/klippy.6.log)

**Comment by Frix-x** [comment]
Can you share your printer.cfg file? Because usually when this happens it's because you did not used any of the accelerometer files as they are the one that make S&T macro automatically available

**Comment by Svennixx** [comment]
> Can you share your printer.cfg file? Because usually when this happens it's because you did not used any of the accelerometer files as they are the one that make S&T macro automatically available

I feel so dumb, thats it! 
I didn't include that because I'm using the new revision of the beacon probe which has an accelerometer build in. And klippain doesn't have file for that yet. 

Shake&Tune is fixed but klippain git is still not being found for update manager.

**Comment by Frix-x** [comment]
Ok so first, this is a good thing :) Then, can you share your beacon accelerometer definition to include it in Klippain ?

Regaridng the "failed to detect repo url", etc... I'm not sure about what could cause this. Can you use SSH and do in the klippain_config folder "git status" and report the result here?

**Comment by Svennixx** [comment]
yeah sure this is all you need to use the beacon (revH) its build in accelerometer:
`[resonance_tester]
accel_chip: beacon`
No pin definitions or adxl345 setup needed. 

git status results:
<img width="194" alt="image" src="https://github.com/Frix-x/klippain/assets/5203461/229753cf-1abb-454d-a602-992cd8420b70">

**Comment by Svennixx** [comment]
Okay not sure what happened, I clicked on the refresh button at the update manager on the UI and it just fixed itself.
Hopefully it will stay like this even on reboots.
