### ISSUE TITLE
aliase n MCU.cfg for the Fysetc ERB are wrong!

### ISSUE THREAD

**Issue by DaWingla** [Frix-x/klippain#529]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.3.0-5-ge2ebb2c4

### Describe the bug and expected behavior

in the MCU.cfg when you choose  Fysetc ERB  the wrong aliases from the Mellow Fly ERCF were insertet. 

MMU_GEAR_STEP=MCU_GEAR_STEP and so on. 

In the Fysetc_ERCF_ERB.cfg is MCU_GEAR_MOTOR_STEP=gpio10.  This causes several errors. I replaced a few aliases . 

MMU_GEAR_STEP=MCU_GEAR_MOTOR_STEP    , MMU_GEAR_DIR=MCU_GEAR_MOTOR_DIR    , MMU_GEAR_ENABLE=MCU_GEAR_MOTOR_EN    , MMU_GEAR_UART=MCU_GEAR_MOTOR_UART    ,
    MMU_GEAR_DIAG=MMCU_GEAR_MOTOR_DIAG   ,
    MMU_SEL_STEP=MCU_SELECTOR_MOTOR_STEP , MMU_SEL_DIR=MCU_SELECTOR_MOTOR_DIR , MMU_SEL_ENABLE=MCU_SELECTOR_MOTOR_EN , MMU_SEL_UART=MCU_SELECTOR_MOTOR_UART ,
    MMU_SEL_DIAG=MCU_SELECTOR_DIAG ,

    MMU_SEL_ENDSTOP=MCU_ENDSTOP    ,
    MMU_SERVO=MCU_SERVO            ,
    MMU_ENCODER=MCU_ENCODER        ,
    MMU_NEOPIXEL=MCU_RGB           ,

    SPI_SCLK=MCU_SPI0_SCK , SPI_MOSI=MCU_SPI0_MOSI , SPI_MISO=MCU_SPI0_MISO ,

but these 

   MMU_PRE_GATE_0=MCU_IO26  , MMU_PRE_GATE_1=MCU_IO10  ,
   MMU_PRE_GATE_2=MCU_IO27  , MMU_PRE_GATE_3=MCU_IO11  ,
   MMU_PRE_GATE_4=MCU_IO28  , MMU_PRE_GATE_5=MCU_IO12  ,
   MMU_PRE_GATE_6=MCU_IO29  , MMU_PRE_GATE_7=MCU_IO24  ,
   MMU_PRE_GATE_8=MCU_IO25  , MMU_PRE_GATE_9=MCU_IO13  ,

i don´t know and get the following error: 
![Screenshot 2024-03-04 131511](https://github.com/Frix-x/klippain/assets/52883784/a0ea898a-7f85-4387-abcb-5e5cfd7e1275)

**Comment by Benoitone** [comment]
yes, realy strange things... I will make the corrections as soon as possible...
