### ISSUE TITLE
Chamber Heat soak time under material_parameters variables.cfg

### ISSUE THREAD

**Issue by smwoodward** [Frix-x/klippain#538]
### Describe the feature or hardware support you'd like

I would like to see the heatsoak time to also be able to be set under the material_parameters

**Comment by Frix-x** [comment]
Good idea. I'll see how to add it for the next version as the material parameter system need a bit of work to make it more flexible...

**Comment by Surion79** [comment]
> Good idea. I'll see how to add it for the next version as the material parameter system need a bit of work to make it more flexible...

including possibility disabling it. For MMU with different types of filament, this is somehow counter intuitive
