### ISSUE TITLE
Override variable for Filament Pull Back at End/Cancel of Print.

### ISSUE THREAD

**Issue by M3HNGRY** [Frix-x/klippain#544]
### Describe the feature or hardware support you'd like

I have a Revo Hotend and would like to have an override variable for filament pull back at the end/cancel of a print. This will help me remove a cold nozzle before a print. Not sure there is another way to do this? Thanks

```
{% elif printer.extruder.can_extrude %}
        # Pull back the filament a little bit
        G92 E0
        G1 E-10 F2100
    {% endif %} 
```

**Comment by rongith** [comment]
To the OP: I created a PR for that: https://github.com/Frix-x/klippain/pull/658
It seems we can't reopen an old issue anymore.
