### ISSUE TITLE
When I am uninstall klippain all the files in config folder are gone!

### ISSUE THREAD

**Issue by adct2luv** [Frix-x/klippain#560]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.3.1-9-g1c5c6623

### Describe the bug and expected behavior

I dont know why this happen
![Screenshot 2024-03-19 at 14 49 59](https://github.com/Frix-x/klippain/assets/30118406/257527ea-cecc-482b-bc29-2d3368a1d27a)

**Comment by EricZimmerman** [comment]
What's in the config folder? What's in the klippain backup folder? 

Did you make your own backup before installing klippain?

**Comment by adct2luv** [comment]
> 
> Did you make your own backup before installing klippain?

Yes, I am so lucky that I have the backup. but I have to setting up new from the ground
