### ISSUE TITLE
Klipper expander

### ISSUE THREAD

**Issue by Foose83** [Frix-x/klippain#562]
### Describe the feature or hardware support you'd like

Bonjour, serait il possible d'ajouter le klipper expander dans les MCUs, je l'utilise pour faire fonctionner les leds sur ma Voron 2.4 parce que la Manta M8P à un problème avec les leds.

### Additional context or information

https://github.com/timmit99/Klipper-Expander

**Comment by Benoitone** [comment]
Bonjour,
j'ai soumis un PR #567 pour Klipper_Expander et également pour Arduino nano
Tu peux regarder ce que tu penses de la partie Klipper Expander

**Comment by Frix-x** [comment]
This was added in the develop branch for a next release :)
