### ISSUE TITLE
Copy backup files to a backup folder

### ISSUE THREAD

**Issue by GhostCuber69** [Frix-x/klippain#564]
### Describe the feature or hardware support you'd like

It would be nice to copy the backup files to a backup folder.
The main folder would look tidier.

---
![image](https://github.com/Frix-x/klippain/assets/162956475/e9f0e1e9-1ba3-4a12-9f1c-e3ddf9071922)

**Comment by Benoitone** [comment]
This backup are not from Klippain… Klipper create them when you use Save Config.
