### ISSUE TITLE
Lift nozzle after nozzle clean and purge

### ISSUE THREAD

**Issue by rugolini** [Frix-x/klippain#572]
### Describe the feature or hardware support you'd like

When the brush and/or purge position are below the bed, the nozzle crashes into the bed when it finishes cleaning or purging if commanded to move to the center of the bed. It would be nice to lift the nozzle above the bed aways after the cleaning and/or purging.

**Comment by Surion79** [comment]
do you have a recommended reference for the target z height for it?
