### ISSUE TITLE
Add the Pause at Layer Functionality for Mainsail

### ISSUE THREAD

**Issue by Elias23** [Frix-x/klippain#585]
### Describe the feature or hardware support you'd like

I'd love to see pause at layer functionality from mainsail to be integrated into klippain.
https://github.com/mainsail-crew/mainsail-config#new-feature-pause-at-next-layer-and-pause-at-layer-

**Comment by Elias23** [comment]
So, as I understand it, there is a new option in mainsail to schedule pauses while printing for either the next layer change or at a certain layer. It requires, as far as I know, the slicer config you mentioned plus 2 new macros(`SET_PAUSE_NEXT_LAYER` and `SET_PAUSE_AT_LAYER`) and a redefinition of the `SET_PRINT_STATS_INFO` macro.
New GUI option:
![image](https://github.com/Frix-x/klippain/assets/5630194/7a1475c6-69d7-4073-acaf-ffdf9c7e555a)
Feature in action via overrides:
![image](https://github.com/Frix-x/klippain/assets/5630194/f8fb4c19-4341-48b2-9543-927c8c234d01)
I assume it would be pretty straight forward to add those macros to klippain, but I might be missing something there.

**Comment by Surion79** [comment]
i created a PR to check. i added the functions as described in the linked repo

**Comment by Elias23** [comment]
Thank you very much.
