### ISSUE TITLE
BTT SB2209 v1.0 incorrect mapping of fans on the toolhead

### ISSUE THREAD

**Issue by kwalters3** [Frix-x/klippain#591]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.3.1-11-g4ff6f5b4

### Describe the bug and expected behavior

The pin aliases for the part cooling fan and the extruder cooling fan are swapped.
Oringinal line is:
PART_FAN=MCU_FAN1_PWM , E_FAN=MCU_FAN2_PWM
should be
PART_FAN=MCU_FAN2_PWM , E_FAN=MCU_FAN1_PWM

Documentation from Bigtreetech shows part fan being connected to fan to VFAN2 and extruder being connected to VFAN1 on the SB0000 daughterboard.

**Comment by Surion79** [comment]
thanks for the info! all other SB configs are correct, just the SB2009 (without RPI) was mixed up
