### ISSUE TITLE
Using the EBB36s endstop port as a klicky port 

### ISSUE THREAD

**Issue by carbon-creations** [Frix-x/klippain#596]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.3.1-11-g4ff6f5b4

### Describe the bug and expected behavior

I don't like using the DuPont connectors for the probe on the EBB36, so I decided to use the end stop port, which actually has a connector on it. i am a bit dense and confused, but I can't figure out how to make this work, the probe should be connected to PG6 
![image](https://github.com/Frix-x/klippain/assets/171506252/b55775cd-439b-48f0-8d14-17a0981ff476)

[probe]
pin: toolhead:PB6

[board_pins ebb_mcu]
mcu: toolhead
aliases:
    E_STEP=MCU_TMCDRIVER_STEP , E_DIR=MCU_TMCDRIVER_DIR , E_ENABLE=MCU_TMCDRIVER_ENABLE , E_TMCUART=MCU_TMCDRIVER_UART ,

    X_STOP=MCU_ENDSTOP1 , Y_STOP=MCU_ENDSTOP2 ,
    PROBE_INPUT=X_STOP ,
    TOOLHEAD_SENSOR=MCU_ENDSTOP3 ,

    E_HEATER=MCU_HOTEND0 , E_TEMPERATURE=MCU_TH0 ,

    PART_FAN=MCU_FAN2 , E_FAN=MCU_FAN1 ,

    STATUS_NEOPIXEL=MCU_RGB ,

    ADXL_CS=MCU_SPI2_CS , ADXL_SCLK=MCU_SPI2_SCLK , ADXL_MISO=MCU_SPI2_MISO , ADXL_MOSI=MCU_SPI2_MOSI ,

### Additional information and klippy.log

[klippy (1).log](https://github.com/user-attachments/files/15526289/klippy.1.log)

**Comment by 24naret** [comment]
I did the following in my mcu.cfg (using tap now but basically the same):

`[include config/mcu_definitions/toolhead/BTT_EBB36-42_v1.2.cfg] # Do not remove this line`
`[board_pins ebb_mcu]`
`mcu: toolhead`
`aliases:`
...
`    PROBE_INPUT=MCU_ENDSTOP1,`
and the later in the remapping section which had been provided by the klippain installer:
`[probe]`
`pin: !toolhead:PROBE_INPUT`
