### ISSUE TITLE
SAVE_CONFIG section 'probe' option 'z_offset' conflicts with included value

### ISSUE THREAD

**Issue by smweil** [Frix-x/klippain#605]
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.3.1-14-gf01c4ca1

### Describe the bug and expected behavior

When running probe_calibrate I cannot save the changes to my config. I'm overriding a few probe commands, but not z_offset. I'm using a Voron TAP for reference. 
Thanks!

### Additional information and klippy.log

[klippy-24.log](https://github.com/user-attachments/files/15906502/klippy-24.log)

**Comment by EricZimmerman** [comment]
You have to just update the value as an override. Save config does not work with klippain

**Comment by Surion79** [comment]
this is a known topic of klipper that using save_config is limited. Due to the nature of the architecture of klippain with many different sets of configuration, makes it impossible to have a correct value being put in printer.cfg.

**Comment by EricZimmerman** [comment]
Danger clipper supports save config regardless of where the actual value is but I don't know if it's going to actually update your printer.cfg or if it would expect to replace the actual section which wouldn't work very well for how things work

**Comment by smweil** [comment]
Got it, thank you.
