### ISSUE TITLE
Ability to toggle `SET_GCODE_OFFSET Z=0` in START_PRINT via variable or startprint actions

### ISSUE THREAD

**Issue by Sureiya** [Frix-x/klippain#617]
### Describe the feature or hardware support you'd like

As some of us are relying on more primitive homing methods (such as on small printers/v0) and are still relying on occasionally baby-stepping or manual adjusting z_offsets between print sessions it would be useful to disable the default behaviour of resetting with `SET_GCODE_OFFSET Z=0` in start_print.cfg. Seems pretty straightforward and easy. Let me know if a PR would be appreciated and I could do it?

**Comment by Surion79** [comment]
for such acitivites, you can overridee a custom module in start print and add it to your print actions list. In this way, you can implment this behaviour for you
