### ISSUE TITLE
Support for BIGTREETECH Manta M4P V2.1-V2.2

### ISSUE THREAD

**Issue by TheGodOFWar1337** [Frix-x/klippain#620]
### Describe the feature or hardware support you'd like

Hi, I would love to see a cfg. template listed as an option for the Manta M4P, using a Manta M4P currently in my V0.

**Comment by Surion79** [comment]
could you provide a PR or a template cfg? probably a M8P as start and remove sections for motors 5-8

**Comment by TheGodOFWar1337** [comment]
I can try modifying mine for klippan. It might take some time to configure and test since my city has major power outgage issues atm , no power .
