### ISSUE TITLE
Lift nozzle before Cleaning

### ISSUE THREAD

**Issue by rugolini** [Frix-x/klippain#623]
### Describe the feature or hardware support you'd like

I commanded a QGL, that failed in the first probing point (no heatsoaking). The toolhead stayed in contact with the bed (I set my z hop really low for my probing, I find it quicker and more accurate) and when I commanded the clean nozzle, the toolhead moved across the bed and "crashed" the nozzle in the (it sits 2mm above bed surface in my case).
It would be Ideal to raize the toolhead before the nozzle cleaning movement.

**Comment by Surion79** [comment]
what do you mean that QGL failed?

Probably a check for min z height and z hop would suffice?
