### ISSUE TITLE
Delta kinematics

### ISSUE THREAD

**Issue by jace** [Frix-x/klippain#629]
### Describe the feature or hardware support you'd like

I just installed Klippain on a new Voron 2.4 build and love how clean it makes my config. I had the stock setup for a day and it was cluttered with comments for the lines I had modified from the sample config. Thanks for the great work!

I'm also upgrading an old delta printer to run Klipper and noticed delta kinematics are not a supported configuration list. It'll be nice to have that.

**Comment by LisziTomi** [comment]
Hello, I am also upgrading an old delta and working on this. Hopefully I can get everything running next week and will push a PR then.
