### ISSUE TITLE
Add support for CNC Taps

### ISSUE THREAD

**Issue by jackmoxley** [Frix-x/klippain#635]
### Describe the feature or hardware support you'd like

Choatic Labs CNC tap, can't handle the sensitivity the default tap is given in the config. So I would like a specialised config that meets the manufactorers settings. I have added a PR to do just that  #632 

### Additional context or information

The change is taken directly from https://github.com/Chaoticlab/CNC-Tap-for-Voron/blob/master/Manual/CNC%20Tap%20V2.cfg but adjusted to match Klippain setup

**Comment by Surion79** [comment]
You can add this in your override. I have also cnc tap of chaoticslab and it works fine with the klippain default settings.
We can only provide one set of settings via klippain in the config sections. Individual changes must be put in overrides.
I don't see the need to add it.

**Comment by jackmoxley** [comment]
I can, I was merely adding the manufacturers recommendations. If you don't want it feel free to close.
