### ISSUE TITLE
Install wiped printers config

### ISSUE THREAD

**Issue by ReaperXD1** [Frix-x/klippain#638]
### Klippain branch

- [X] I confirm using the main branch

### Version

v0.12.0-274-gd7d9092a

### Describe the bug and expected behavior

Upon installation via SSH, all my configuration files disappeared without a trace. I am beyond frustrated right now and I feel like issues like this should really be taken seriously. This has cost me big time as I had a very complex setup, which has taken almost a year to achieve. I really have no words right now.

**Comment by EricZimmerman** [comment]
No backup? Maybe next time. 

I would suggest getting a klippy.log as it will contain your cfg.

**Comment by ReaperXD1** [comment]
I have a backup from a month ago, but things have changed since. I am pretty mad, how does a simple install cause this?

**Comment by EricZimmerman** [comment]
It should have backed them up to klippain backup in home folder. 

Always have backups. Use my GitHub backup writeup and avoid this next time. 

What if your SD card died??

**Comment by ReaperXD1** [comment]
SD card is okay, just checked via WINSCP and my files are there thankfully. I'm going to do backups through KIAUH start fresh. Frustrating. I should setup auto backups, that's a good idea. Never occured to me. This is still very inconveniencing. Would a Klippy log still be relevant?

**Comment by EricZimmerman** [comment]
Doesn't matter now. You have your configs. Get them OFF the pi. Use my GitHub writeup.
