### ISSUE TITLE
Add Input Shaper Workflow and vibration graph documentation

### ISSUE THREAD

**Issue by voidtrance** [Frix-x/klippain#92]
There doesn't seem to be any documentation describing how to interpret the belt tension graphs that your scripts generate. It would be useful to know how to read the graphs:

* What do the peaks represent?
* What should the user be looking for?
* How to fix issues?

Thank you.

**Comment by EricZimmerman** [comment]
It would be nice to have a read me with a bunch of compon graphs, what is good, what is bad, how to tweak etc. Same with input shaper really

**Comment by Frix-x** [comment]
Hey,
Thanks for raising an issue on this topic. You're right, I get a lot of questions on the Discord about this subject and I will try to compile a documentation section to interpret them :)

**Comment by Frix-x** [comment]
Hey, I'm currently working on some documentation. It's actually a WIP but you can have a look in #129

**Comment by Frix-x** [comment]
Done in 2c41a777cc9a42c5ba481bbba610ba8490e7287c

**Comment by Frix-x** [comment]
Closing as Klippain v4 is merged and released :)
